In [89]:
import pandas as pd
import numpy as np

In [90]:
d=pd.read_csv(r"C:\geethanjaliexternship\abalone_data.csv")

In [91]:
d.head()

column_a  column_b  column_c  column_d  column_e  column_f  column_g  \
0        M     0.455     0.365     0.095    0.5140    0.2245    0.1010   
1        M     0.350     0.265     0.090    0.2255    0.0995    0.0485   
2        F     0.530     0.420     0.135    0.6770    0.2565    0.1415   
3        M     0.440     0.365     0.125    0.5160    0.2155    0.1140   
4        I     0.330     0.255     0.080    0.2050    0.0895    0.0395   

   column_h  column_i  
0     0.150      15.0  
1     0.070       7.0  
2     0.210       9.0  
3     0.155      10.0  
4     0.055       7.0

In [92]:
d["column_a"].unique()

array(['M', 'F', 'I'], dtype=object)

In [93]:
d.isnull().sum()

column_a    0
column_b    0
column_c    0
column_d    0
column_e    1
column_f    1
column_g    1
column_h    1
column_i    1
dtype: int64

In [94]:
d["column_e"].fillna(d["column_e"].mean(),inplace=True)

In [95]:
d["column_f"].fillna(d["column_f"].mean(),inplace=True)

In [96]:
d["column_g"].fillna(d["column_g"].mean(),inplace=True)

In [97]:
d["column_h"].fillna(d["column_h"].mean(),inplace=True)

In [98]:
d["column_i"].fillna(d["column_i"].mean(),inplace=True)

In [99]:
d.isnull().sum()

column_a    0
column_b    0
column_c    0
column_d    0
column_e    0
column_f    0
column_g    0
column_h    0
column_i    0
dtype: int64

In [130]:
x=d.iloc[:,1:9].values
y=d.iloc[:,0:1].values

In [131]:
x

array([[ 0.455     ,  0.365     ,  0.095     , ...,  0.101     ,
         0.15      , 15.        ],
       [ 0.35      ,  0.265     ,  0.09      , ...,  0.0485    ,
         0.07      ,  7.        ],
       [ 0.53      ,  0.42      ,  0.135     , ...,  0.1415    ,
         0.21      ,  9.        ],
       ...,
       [ 0.32      ,  0.25      ,  0.08      , ...,  0.034     ,
         0.06      ,  9.        ],
       [ 0.43      ,  0.34      ,  0.125     , ...,  0.061     ,
         0.146     , 14.        ],
       [ 0.565     ,  0.45      ,  0.        , ...,  0.1791053 ,
         0.23773037,  9.9376947 ]])

In [132]:
y

array([['M'],
       ['M'],
       ['F'],
       ...,
       ['I'],
       ['I'],
       ['M']], dtype=object)

In [133]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
one = OneHotEncoder()
z = one.fit_transform(y[:,0:1]).toarray()
y = np.delete(y,0,axis = 1)
y = np.concatenate((z,y),axis = 1)

In [134]:
print(y)

[[0.0 0.0 1.0]
 [0.0 0.0 1.0]
 [1.0 0.0 0.0]
 ...
 [0.0 1.0 0.0]
 [0.0 1.0 0.0]
 [0.0 0.0 1.0]]


In [135]:
y.shape

(3211, 3)

In [136]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [137]:
x_train = np.asarray(x_train).astype('float32')
x_test = np.asarray(x_test).astype('float32')
y_train = np.asarray(y_train).astype('float32')
y_test = np.asarray(y_test).astype('float32')

In [138]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [139]:
x_train.shape

(2568, 8)

In [140]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [141]:
cat = Sequential()

In [142]:
cat.add(Dense(7,kernel_initializer = "random_uniform",activation ="relu"))

In [143]:
cat.add(Dense(14,kernel_initializer = "random_uniform",activation ="relu"))

In [144]:
cat.add(Dense(3,kernel_initializer = "random_uniform",activation ="softmax"))

In [145]:
cat.compile("adam","categorical_crossentropy",metrics = ["accuracy"])

In [146]:
cat.fit(x_train,y_train,batch_size = 23, epochs=100)

Epoch 1/100
112/112 [==============================] - 1s 2ms/step - loss: 1.0855 - accuracy: 0.4513
Epoch 2/100
112/112 [==============================] - 0s 2ms/step - loss: 0.9005 - accuracy: 0.5254
Epoch 3/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8764 - accuracy: 0.5457
Epoch 4/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8740 - accuracy: 0.5352
Epoch 5/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8747 - accuracy: 0.5348
Epoch 6/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8772 - accuracy: 0.5399
Epoch 7/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8649 - accuracy: 0.5391
Epoch 8/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8634 - accuracy: 0.5452
Epoch 9/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8885 - accuracy: 0.5279
Epoch 10/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8814 - accura

112/112 [==============================] - 0s 2ms/step - loss: 0.8335 - accuracy: 0.5647
Epoch 82/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8231 - accuracy: 0.5677
Epoch 83/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8413 - accuracy: 0.5650
Epoch 84/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8467 - accuracy: 0.5463
Epoch 85/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8437 - accuracy: 0.5526
Epoch 86/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8497 - accuracy: 0.5562
Epoch 87/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8382 - accuracy: 0.5596
Epoch 88/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8225 - accuracy: 0.5676
Epoch 89/100
112/112 [==============================] - 0s 2ms/step - loss: 0.8314 - accuracy: 0.5763
Epoch 90/100
112/112 [==============================] - 0s 1ms/step - loss: 0.8169 - accuracy: 

In [147]:
x_train.shape

(2568, 8)

In [148]:
y_train.shape

(2568, 3)

In [149]:
ypred = cat.predict(x_test)

In [150]:
ypred

array([[0.48541334, 0.0115963 , 0.50299037],
       [0.02994487, 0.883657  , 0.0863982 ],
       [0.4643214 , 0.06216912, 0.4735095 ],
       ...,
       [0.35016248, 0.25207138, 0.39776614],
       [0.21559533, 0.46783933, 0.3165654 ],
       [0.30007544, 0.26819453, 0.43173003]], dtype=float32)

In [151]:
ypred[2]

array([0.4643214 , 0.06216912, 0.4735095 ], dtype=float32)

In [152]:
y_test[2]

array([1., 0., 0.], dtype=float32)

In [153]:
d.head()

column_a  column_b  column_c  column_d  column_e  column_f  column_g  \
0        M     0.455     0.365     0.095    0.5140    0.2245    0.1010   
1        M     0.350     0.265     0.090    0.2255    0.0995    0.0485   
2        F     0.530     0.420     0.135    0.6770    0.2565    0.1415   
3        M     0.440     0.365     0.125    0.5160    0.2155    0.1140   
4        I     0.330     0.255     0.080    0.2050    0.0895    0.0395   

   column_h  column_i  
0     0.150      15.0  
1     0.070       7.0  
2     0.210       9.0  
3     0.155      10.0  
4     0.055       7.0

In [155]:
cat.predict_classes(sc.transform([[0.4555,0.095,0.5140,0.2245,0.2560,0.1010,0.150,15.0]]))

C:\Users\ssc\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


array([0], dtype=int64)