In [1]:
import pandas as pd
import numpy as np

In [2]:
d=pd.read_csv("titanic.csv")

In [3]:
d.head()

Survived                                               Name     Sex  \
0         0                             Mr. Owen Harris Braund    male   
1         1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female   
2         1                              Miss. Laina Heikkinen  female   
3         1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female   
4         0                            Mr. William Henry Allen    male   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  Pclass   Age  
0                        1                        0   7.2500       3  22.0  
1                        1                        0  71.2833       1  38.0  
2                        0                        0   7.9250       3  26.0  
3                        1                        0  53.1000       1  35.0  
4                        0                        0   8.0500       3  35.0

In [4]:
d.tail()

Survived                            Name     Sex  \
882         0            Rev. Juozas Montvila    male   
883         1     Miss. Margaret Edith Graham  female   
884         0  Miss. Catherine Helen Johnston  female   
885         1            Mr. Karl Howell Behr    male   
886         0              Mr. Patrick Dooley    male   

     Siblings/Spouses Aboard  Parents/Children Aboard   Fare  Pclass   Age  
882                        0                        0  13.00       2  27.0  
883                        0                        0  30.00       1  19.0  
884                        1                        2  23.45       3   7.0  
885                        0                        0  30.00       1  26.0  
886                        0                        0   7.75       3  32.0

In [5]:
d["Fare"].unique

<bound method Series.unique of 0        7.2500
1       71.2833
2        7.9250
3       53.1000
4        8.0500
5        8.4583
6       51.8625
7       21.0750
8       11.1333
9       30.0708
10      16.7000
11      26.5500
12       8.0500
13      31.2750
14       7.8542
15      16.0000
16      29.1250
17      13.0000
18      18.0000
19       7.2250
20      26.0000
21      13.0000
22       8.0292
23      35.5000
24      21.0750
25      31.3875
26       7.2250
27     263.0000
28       7.8792
29       7.8958
         ...   
857     11.5000
858     25.9292
859     69.5500
860     13.0000
861     13.0000
862     13.8583
863     50.4958
864      9.5000
865     11.1333
866      7.8958
867     52.5542
868      5.0000
869      9.0000
870     24.0000
871      7.2250
872      9.8458
873      7.8958
874      7.8958
875     83.1583
876     26.0000
877      7.8958
878     10.5167
879     10.5000
880      7.0500
881     29.1250
882     13.0000
883     30.0000
884     23.4500
885     30.0000
886      

In [6]:
d.isnull().any()

Survived                   False
Name                       False
Sex                        False
Siblings/Spouses Aboard    False
Parents/Children Aboard    False
Fare                       False
Pclass                     False
Age                        False
dtype: bool

In [10]:
x=d.iloc[:,2:8].values
y=d.iloc[:,0:1].values

In [11]:
x

array([['male', 1, 0, 7.25, 3, 22.0],
       ['female', 1, 0, 71.2833, 1, 38.0],
       ['female', 0, 0, 7.925, 3, 26.0],
       ...,
       ['female', 1, 2, 23.45, 3, 7.0],
       ['male', 0, 0, 30.0, 1, 26.0],
       ['male', 0, 0, 7.75, 3, 32.0]], dtype=object)

In [9]:
y

array([[0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
    

In [12]:
x.shape

(887, 6)

In [13]:
y.shape

(887, 1)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([("oh", OneHotEncoder(),[0])],remainder = "passthrough") # conerts data to binary format
x = ct.fit_transform(x)

In [15]:
x

array([[0.0, 1.0, 1, ..., 7.25, 3, 22.0],
       [1.0, 0.0, 1, ..., 71.2833, 1, 38.0],
       [1.0, 0.0, 0, ..., 7.925, 3, 26.0],
       ...,
       [1.0, 0.0, 1, ..., 23.45, 3, 7.0],
       [0.0, 1.0, 0, ..., 30.0, 1, 26.0],
       [0.0, 1.0, 0, ..., 7.75, 3, 32.0]], dtype=object)

In [17]:
x.shape


(887, 7)

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)

In [19]:
x_train.shape

(709, 7)

In [20]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [21]:
x_train

array([[-0.74486547,  0.74486547, -0.49076818, ..., -0.49314838,
         0.86315976,  0.03586517],
       [ 1.34252432, -1.34252432, -0.49076818, ...,  0.87213561,
        -1.52738816,  0.6114777 ],
       [ 1.34252432, -1.34252432, -0.49076818, ..., -0.39755953,
         0.86315976, -1.97877871],
       ...,
       [-0.74486547,  0.74486547, -0.49076818, ..., -0.05196905,
        -1.52738816,  0.1797683 ],
       [-0.74486547,  0.74486547, -0.49076818, ..., -0.37455179,
        -0.3321142 , -0.10803797],
       [-0.74486547,  0.74486547, -0.49076818, ..., -0.43772487,
         0.86315976, -0.75560207]])

In [22]:
from tensorflow.keras.models import Sequential #used 2 initialise the model
from tensorflow.keras.layers import Dense #used 2 add layers of ann model

In [23]:
ann=Sequential()

In [26]:
ann.add(Dense(7,kernel_initializer = "random_uniform", activation ="relu"))

In [27]:
ann.add(Dense(14,kernel_initializer = "random_uniform", activation ="relu"))

In [32]:
ann.add(Dense(1,kernel_initializer = "random_uniform", activation ="sigmoid"))

In [33]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [35]:
ann.fit(x_train,y_train,batch_size=32,epochs=40)

Epoch 1/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.6037
Epoch 2/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6716 - accuracy: 0.6037
Epoch 3/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6716 - accuracy: 0.6037
Epoch 4/40
23/23 [==============================] - 0s 3ms/step - loss: 0.6716 - accuracy: 0.6037
Epoch 5/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.6037
Epoch 6/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6714 - accuracy: 0.6037
Epoch 7/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6722 - accuracy: 0.6037
Epoch 8/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6717 - accuracy: 0.6037
Epoch 9/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6716 - accuracy: 0.6037
Epoch 10/40
23/23 [==============================] - 0s 2ms/step - loss: 0.6718 - accuracy: 0.6037
Epoch 11/40
23/23 [

In [36]:
ypred=ann.predict(x_test)

In [37]:
ypred

array([[0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.39643162],
       [0.396

In [38]:
ypred>0.5

array([[False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [39]:
y_test

array([[0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [40]:
d.head(1)

Survived                    Name   Sex  Siblings/Spouses Aboard  \
0         0  Mr. Owen Harris Braund  male                        1   

   Parents/Children Aboard  Fare  Pclass   Age  
0                        0  7.25       3  22.0

In [48]:
yp=ann.predict(sc.transform(ct.transform([["male",1,0,7.25,3,22]])))

In [49]:
yp

array([[0.39643162]], dtype=float32)

In [50]:
yp>0.5

array([[False]])

In [51]:
d.head()

Survived                                               Name     Sex  \
0         0                             Mr. Owen Harris Braund    male   
1         1  Mrs. John Bradley (Florence Briggs Thayer) Cum...  female   
2         1                              Miss. Laina Heikkinen  female   
3         1        Mrs. Jacques Heath (Lily May Peel) Futrelle  female   
4         0                            Mr. William Henry Allen    male   

   Siblings/Spouses Aboard  Parents/Children Aboard     Fare  Pclass   Age  
0                        1                        0   7.2500       3  22.0  
1                        1                        0  71.2833       1  38.0  
2                        0                        0   7.9250       3  26.0  
3                        1                        0  53.1000       1  35.0  
4                        0                        0   8.0500       3  35.0

In [52]:
yp=ann.predict(sc.transform(ct.transform([["female",1,0,71.2833,1,38]])))

In [53]:
yp

array([[0.39643162]], dtype=float32)

In [54]:
yp>0.5

array([[False]])