In [4]:
import pandas as pd
import numpy as np

In [5]:
d=pd.read_csv(r"C:\geethanjaliexternship\nba_logreg.csv")

In [6]:
d.head()

name  gp   min  pts  fgm  fga    fg  3p_made  3pa    3p  ...  \
0   Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   
1  Andrew Harrison  35  26.9  7.2  2.0  6.7  29.6      0.7  2.8  23.5  ...   
2   JaKarr Sampson  74  15.3  5.2  2.0  4.7  42.2      0.4  1.7  24.4  ...   
3      Malik Sealy  58  11.6  5.7  2.3  5.5  42.6      0.1  0.5  22.6  ...   
4      Matt Geiger  48  11.5  4.5  1.6  3.0  52.4      0.0  0.1   0.0  ...   

   fta    ft  oreb  dreb  reb  ast  stl  blk  tov  target_5yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  
1  3.4  76.5   0.5   2.0  2.4  3.7  1.1  0.5  1.6          0.0  
2  1.3  67.0   0.5   1.7  2.2  1.0  0.5  0.3  1.0          0.0  
3  1.3  68.9   1.0   0.9  1.9  0.8  0.6  0.1  1.0          1.0  
4  1.9  67.4   1.0   1.5  2.5  0.3  0.3  0.4  0.8          1.0  

[5 rows x 21 columns]

In [7]:
d.isnull().any()

name           False
gp             False
min            False
pts            False
fgm            False
fga            False
fg             False
3p_made        False
3pa            False
3p              True
ftm            False
fta            False
ft             False
oreb           False
dreb           False
reb            False
ast            False
stl            False
blk            False
tov            False
target_5yrs    False
dtype: bool

In [8]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1340 entries, 0 to 1339
Data columns (total 21 columns):
name           1340 non-null object
gp             1340 non-null int64
min            1340 non-null float64
pts            1340 non-null float64
fgm            1340 non-null float64
fga            1340 non-null float64
fg             1340 non-null float64
3p_made        1340 non-null float64
3pa            1340 non-null float64
3p             1329 non-null float64
ftm            1340 non-null float64
fta            1340 non-null float64
ft             1340 non-null float64
oreb           1340 non-null float64
dreb           1340 non-null float64
reb            1340 non-null float64
ast            1340 non-null float64
stl            1340 non-null float64
blk            1340 non-null float64
tov            1340 non-null float64
target_5yrs    1340 non-null float64
dtypes: float64(19), int64(1), object(1)
memory usage: 219.9+ KB


In [11]:
d["3p"].mean()

19.308126410835207

In [12]:
d["3p"].fillna(d["3p"].mean(),inplace = True)

In [13]:
x=d.iloc[:,1:20].values
y=d.iloc[:,20].values

In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test  = train_test_split(x,y , test_size = 0.2 , random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc =StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [16]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

In [17]:
ann=Sequential()

In [18]:
ann.add(Dense(19,kernel_initializer = "random_uniform", activation ="relu"))

In [19]:
ann.add(Dense(38,kernel_initializer = "random_uniform", activation ="relu"))

In [20]:
ann.add(Dense(1,kernel_initializer = "random_uniform", activation ="sigmoid"))

In [23]:
ann.compile("adam","binary_crossentropy",metrics=["accuracy"])

In [24]:
ann.fit(x_train,y_train,batch_size=32,epochs=500)

Epoch 1/500
34/34 [==============================] - 4s 5ms/step - loss: 0.6896 - accuracy: 0.6177
Epoch 2/500
34/34 [==============================] - 0s 1ms/step - loss: 0.6447 - accuracy: 0.6218
Epoch 3/500
34/34 [==============================] - 0s 2ms/step - loss: 0.5981 - accuracy: 0.6853
Epoch 4/500
34/34 [==============================] - 0s 2ms/step - loss: 0.5839 - accuracy: 0.7124
Epoch 5/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5826 - accuracy: 0.7077
Epoch 6/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5580 - accuracy: 0.7085
Epoch 7/500
34/34 [==============================] - 0s 2ms/step - loss: 0.5582 - accuracy: 0.7071
Epoch 8/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5503 - accuracy: 0.7292
Epoch 9/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5689 - accuracy: 0.7103
Epoch 10/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5331 - accuracy: 0.7375
Epoch 11/

Epoch 83/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4968 - accuracy: 0.7454
Epoch 84/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4780 - accuracy: 0.7788
Epoch 85/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4884 - accuracy: 0.7672
Epoch 86/500
34/34 [==============================] - 0s 2ms/step - loss: 0.5057 - accuracy: 0.7343
Epoch 87/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4767 - accuracy: 0.7600
Epoch 88/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4951 - accuracy: 0.7603
Epoch 89/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4955 - accuracy: 0.7573
Epoch 90/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4941 - accuracy: 0.7621
Epoch 91/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4845 - accuracy: 0.7643
Epoch 92/500
34/34 [==============================] - 0s 1ms/step - loss: 0.5042 - accuracy: 0.7545


34/34 [==============================] - 0s 1ms/step - loss: 0.4281 - accuracy: 0.7995
Epoch 164/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4422 - accuracy: 0.7787
Epoch 165/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4672 - accuracy: 0.7709
Epoch 166/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4232 - accuracy: 0.7905
Epoch 167/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4319 - accuracy: 0.8076
Epoch 168/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4561 - accuracy: 0.7718
Epoch 169/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4401 - accuracy: 0.7803
Epoch 170/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4139 - accuracy: 0.8057
Epoch 171/500
34/34 [==============================] - 0s 2ms/step - loss: 0.4299 - accuracy: 0.7813
Epoch 172/500
34/34 [==============================] - 0s 1ms/step - loss: 0.4273 - accuracy: 0.7985
Epoc

34/34 [==============================] - 0s 2ms/step - loss: 0.3900 - accuracy: 0.8168
Epoch 245/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3735 - accuracy: 0.8308
Epoch 246/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3775 - accuracy: 0.8379
Epoch 247/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3811 - accuracy: 0.8379
Epoch 248/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3837 - accuracy: 0.8129
Epoch 249/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3802 - accuracy: 0.8231
Epoch 250/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3995 - accuracy: 0.8156
Epoch 251/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3767 - accuracy: 0.8265
Epoch 252/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3765 - accuracy: 0.8409
Epoch 253/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3844 - accuracy: 0.8140
Epoc

34/34 [==============================] - 0s 1ms/step - loss: 0.3447 - accuracy: 0.8365
Epoch 326/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3525 - accuracy: 0.8280
Epoch 327/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3203 - accuracy: 0.8608
Epoch 328/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3491 - accuracy: 0.8354
Epoch 329/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3391 - accuracy: 0.8385
Epoch 330/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3415 - accuracy: 0.8168
Epoch 331/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3661 - accuracy: 0.8262
Epoch 332/500
34/34 [==============================] - 0s 1ms/step - loss: 0.3451 - accuracy: 0.8349
Epoch 333/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3542 - accuracy: 0.8331
Epoch 334/500
34/34 [==============================] - 0s 990us/step - loss: 0.3281 - accuracy: 0.8517
Ep

34/34 [==============================] - 0s 2ms/step - loss: 0.3271 - accuracy: 0.8511
Epoch 407/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3238 - accuracy: 0.8482
Epoch 408/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2893 - accuracy: 0.8722
Epoch 409/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3206 - accuracy: 0.8463
Epoch 410/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3329 - accuracy: 0.8367
Epoch 411/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2923 - accuracy: 0.8604
Epoch 412/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2953 - accuracy: 0.8568
Epoch 413/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2852 - accuracy: 0.8778
Epoch 414/500
34/34 [==============================] - 0s 2ms/step - loss: 0.3207 - accuracy: 0.8587
Epoch 415/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2940 - accuracy: 0.8796
Epoc

34/34 [==============================] - 0s 1ms/step - loss: 0.2829 - accuracy: 0.8676
Epoch 487/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2999 - accuracy: 0.8655
Epoch 488/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2863 - accuracy: 0.8570
Epoch 489/500
34/34 [==============================] - 0s 3ms/step - loss: 0.2884 - accuracy: 0.8773
Epoch 490/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2958 - accuracy: 0.8745
Epoch 491/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2602 - accuracy: 0.8900
Epoch 492/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2830 - accuracy: 0.8622
Epoch 493/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2885 - accuracy: 0.8618
Epoch 494/500
34/34 [==============================] - 0s 2ms/step - loss: 0.2554 - accuracy: 0.8858
Epoch 495/500
34/34 [==============================] - 0s 1ms/step - loss: 0.2700 - accuracy: 0.8872
Epoc

In [25]:
ypred=ann.predict(x_test)

In [26]:
d.head(1)

name  gp   min  pts  fgm  fga    fg  3p_made  3pa    3p  ...  \
0  Brandon Ingram  36  27.4  7.4  2.6  7.6  34.7      0.5  2.1  25.0  ...   

   fta    ft  oreb  dreb  reb  ast  stl  blk  tov  target_5yrs  
0  2.3  69.9   0.7   3.4  4.1  1.9  0.4  0.4  1.3          0.0  

[1 rows x 21 columns]

In [27]:
yp=ann.predict(sc.transform([[36,274,7.4,2.6,7.6,34.7,0.5,2.1,25.0,1.6,2.3,69.9,0.7,3.4,4.1,1.9,0.1,0.4,1.3]]))

In [28]:
yp

array([[0.]], dtype=float32)

In [29]:
yp>0.5

array([[False]])

In [30]:
yp=ann.predict(sc.transform([[40,280,7.9,3.6,44.7,8.5,5.1,55.0,5.6,2.8,69.7,2.7,5.4,2.1,8.9,0.3,0.2,1.5,5.2]]))

In [31]:
yp>0.5

array([[ True]])